{{- if or (eq .Values.frontend.type "vue") (eq .Values.frontend.type "both") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-vue-service
  labels:
    app: frontend-vue-service
spec:
  replicas: {{ .Values.frontendVueService.replicaCount }}
  selector:
    matchLabels:
      app: frontend-vue-service
  template:
    metadata:
      labels:
        app: frontend-vue-service
    spec:
      containers:
        - name: frontend-vue-service
          image: "{{ .Values.image.repository }}/{{ .Values.frontendVueService.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8084
              protocol: TCP
          env:
            - name: SPA_KEYCLOAK_URL
              value: {{ .Values.keycloak.publicUrl | quote }}
            - name: SPA_RESOURCE_SERVER_URL
              value: ""
            - name: SPA_CLIENT_SERVICE_URL
              value: ""
            {{- if eq .Values.frontend.type "both" }}
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: /vue
            {{- end }}
            - name: SERVER_FORWARD_HEADERS_STRATEGY
              value: framework
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-vue-service
spec:
  type: {{ .Values.frontendVueService.service.type }}
  ports:
    - port: {{ .Values.frontendVueService.service.port }}
      targetPort: 8084
      protocol: TCP
      name: http
  selector:
    app: frontend-vue-service
{{- end }}