{{- if or (eq .Values.frontend.type "htmx") (eq .Values.frontend.type "both") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-htmx-service
  labels:
    app: frontend-htmx-service
spec:
  replicas: {{ .Values.frontendHtmxService.replicaCount }}
  selector:
    matchLabels:
      app: frontend-htmx-service
  template:
    metadata:
      labels:
        app: frontend-htmx-service
    spec:
      containers:
        - name: frontend-htmx-service
          image: "{{ .Values.image.repository }}/{{ .Values.frontendHtmxService.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8083
              protocol: TCP
          env:
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI
              value: "http://keycloak:{{ .Values.keycloak.port }}/realms/demo"
            - name: RESOURCE_SERVER_BASE_URL
              value: "http://resource-server:{{ .Values.resourceServer.service.port }}"
            - name: CLIENT_SERVICE_BASE_URL
              value: "http://client-service:{{ .Values.clientService.service.port }}"
            - name: SERVER_FORWARD_HEADERS_STRATEGY
              value: framework
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-htmx-service
spec:
  type: {{ .Values.frontendHtmxService.service.type }}
  ports:
    - port: {{ .Values.frontendHtmxService.service.port }}
      targetPort: 8083
      protocol: TCP
      name: http
  selector:
    app: frontend-htmx-service
{{- end }}
