{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  annotations:
    {{- if .Values.ingress.className }}
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          {{- if eq .Values.frontend.type "both" }}
          - path: /vue
            pathType: Prefix
            backend:
              service:
                name: frontend-vue-service
                port:
                  number: {{ .Values.frontendVueService.service.port }}
          {{- end }}
          - path: /
            pathType: Prefix
            backend:
              {{- if eq .Values.frontend.type "vue" }}
                name: frontend-vue-service
                port:
                  number: {{ .Values.frontendVueService.service.port }}
              {{- else }}
                name: frontend-htmx-service
                port:
                  number: {{ .Values.frontendHtmxService.service.port }}
              {{- end }}
{{- end }}
