server:
  port: 8084

spring:
  application:
    name: frontend-vue-service

spa:
  keycloak-url: http://localhost:8080
  resource-server-url: http://localhost:8081
  client-service-url: http://localhost:8082