server:
  port: 8081

spring:
  application:
    name: resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/demo

logging:
  level:
    io.mendirl.demo.resourceserver: DEBUG
    org.springframework.security: INFO
    org.springframework.security.oauth2: DEBUG
